### ISSUE TITLE
[Security] 

### ISSUE THREAD

**Issue by mindoverlord** [ukrblx/UK-s-Group-Finder#1]
After using the program, I've noticed an intriguing aspect regarding its functionality when hosted on platforms like Replit. The program's usage of webhooks presents a potential security vulnerability. Specifically, users' webhooks are exposed, creating a risk of unauthorized access and potential abuse. Other then that great program it is super fast.

**Comment by ukrblx** [comment]
For now, I'll create a Replit template with security features, and later on, I'll integrate it into the UI.

**Comment by mindoverlord** [comment]
Alright, also noticed your website isn't working. I can make a pull request to fix it.

**Comment by ukrblx** [comment]
> Alright, also noticed your website isn't working. I can make a pull request to fix it.

Sounds, good!
